export const ANABIN_COUNTRIES = [
    'AF',
    'EG',
    'AL',
    'DZ',
    'AO',
    'AG',
    'AR',
    'AM',
    'AZ',
    'ET',
    'AU',
    'BH',
    'BD',
    'BE',
    'BZ',
    'BJ',
    'BO',
    'BA',
    'BW',
    'BR',
    'BN',
    'BG',
    'BF',
    'BI',
    'KY',
    'CL',
    'CN',
    'CR',
    'CI',
    'DK',
    'DO',
    'EC',
    'SV',
    'ER',
    'EE',
    'FJ',
    'FI',
    'FR',
    'GA',
    'GM',
    'GE',
    'GH',
    'GR',
    'GL',
    'GB',
    'GT',
    'GN',
    'GW',
    'HN',
    'HK',
    'IN',
    'ID',
    'IQ',
    'IR',
    'IE',
    'IS',
    'IL',
    'IT',
    'JM',
    'JP',
    'YE',
    'JO',
    'KH',
    'CM',
    'CA',
    'CV',
    'KZ',
    'KE',
    'KG',
    'CO',
    'CG',
    'CD',
    'KP',
    'KR',
    'XK',
    'HR',
    'CU',
    'LA',
    'LV',
    'LB',
    'LR',
    'LY',
    'LI',
    'LT',
    'LU',
    'MO',
    'MG',
    'MW',
    'MY',
    'ML',
    'MT',
    'MA',
    'MU',
    'MK',
    'MX',
    'MD',
    'ME',
    'MZ',
    'MM',
    'NA',
    'NP',
    'NZ',
    'NI',
    'NL',
    'NE',
    'NG',
    'MC',
    'NO',
    'OM',
    'AT',
    'TL',
    'PK',
    'PS',
    'PA',
    'PG',
    'PY',
    'PE',
    'PH',
    'PL',
    'PT',
    'QA',
    'RW',
    'RO',
    'RU',
    'ZM',
    'SM',
    'SA',
    'SE',
    'CH',
    'SN',
    'RS',
    'ZW',
    'SG',
    'SK',
    'SI',
    'ES',
    'LK',
    'KN',
    'LC',
    'ZA',
    'SD',
    'SY',
    'TJ',
    'TW',
    'TZ',
    'TH',
    'TG',
    'TD',
    'CZ',
    'TN',
    'TR',
    'TM',
    'TC',
    'UG',
    'UA',
    'HU',
    'UY',
    'US',
    'UZ',
    'VA',
    'VE',
    'AE',
    'VN',
    'BY',
    'CF',
    'CY',
    'CY',
  ];

  export enum GermanWorkFieldId {
    ArchitectsPlannersSurveyorsDesigners = 216,
    DatabaseNetworkProfessionals = 252,
    ElectrotechnologyEngineers = 215,
    EngineeringProfessionals = 214,
    LifeScienceProfessionals = 213,
    MathematiciansActuariesStatisticians = 212,
    MedicalDoctors = 221,
    Other = 0,
    PhysicalAndEarthScienceProfessionals = 211,
    SoftwareApplicationsDevelopersAnalysts = 251,
  }

  export const WORK_FIELD_LABELS = {
    0: 'Other',
    1: 'Managers',
    112: 'Managing directors and chief executives',
    1212: 'Human resource managers',
    122: 'Sales, marketing, PR and development managers',
    19: 'Other managers',
    2: 'Professionals',
    21: 'Science and engineering professionals',
    211: 'Physical and earth science professionals',
    2166: 'Designers',
    212: 'Mathematicians, actuaries and statisticians',
    213: 'Life science professionals',
    214: 'Engineering professionals (excluding electrotechnology)',
    215: 'Electrotechnology engineers',
    216: 'Architects, planners, surveyors and designers',
    22: 'Health professionals',
    23: 'Teaching professionals',
    24: 'Business and administration professionals',
    241: 'Finance professionals',
    242: 'Administration professionals',
    243: 'Sales, marketing and public relations professionals',
    25: 'Software developers and software engineers',
    26: 'Legal, social and cultural professionals',
    263: 'Social and religious professionals',
    264: 'Authors, journalists and linguists',
    265: 'Creative and performing artists',
    3: 'Technicians and associate professionals',
    31: 'Science and engineering associate professionals',
    311: 'Physical and engineering science technicians',
    312: 'Mining, manufacturing and construction supervisors',
    313: 'Process control technicians',
    314: 'Life science technicians and related associate professionals',
    315: 'Ship and aircraft controllers and technicians',
    32: 'Health associate professionals',
    33: 'Business and administration associate professionals',
    34: 'Legal, social, cultural and related associate professionals',
    35: 'Information and communications technicians',
    4: 'Clerical support workers',
    5: 'Service and sales workers',
    51: 'Personal service workers',
    511: 'Travel attendants, conductors and guides',
    512: 'Cooks',
    515: 'Building and housekeeping supervisors',
    516: 'Other personal services workers',
    52: 'Sales workers',
    54: 'Protective services workers',
    6: 'Skilled agricultural, forestry and fishery workers',
    61: 'Market-oriented skilled agricultural workers',
    62: 'Market-oriented skilled forestry, fishery and hunting workers',
    63: 'Subsistence farmers, fishers, hunters and gatherers',
    7: 'Craft and related trades workers',
    71: 'Building and related trades workers, excluding electricians',
    72: 'Metal, machinery and related trades workers',
    73: 'Handicraft and printing workers',
    74: 'Electrical and electronic trades workers',
    75: 'Food processing, wood working, garment and other craft and related trades workers',
    8: 'Plant and machine operators, and assemblers',
    81: 'Stationary plant and machine operators',
    83: 'Drivers and mobile plant operators',
    9: 'Elementary occupations',
  };